<a href="https://colab.research.google.com/github/rachakondasaivarshini/DS-EXPS/blob/main/DS_exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
addition = a + b
subtraction = b - a
multiplication = a * b
division = b / a
print("Array a:", a)
print("Array b:", b)
print("\nAddition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)




Array a: [1 2 3 4]
Array b: [10 20 30 40]

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


In [2]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))

Mean: 30.0
Median: 30.0
Variance: 200.0
Standard Deviation: 14.142135623730951


In [3]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])

print("Original Matrix:")
print(arr)

reshaped_arr = arr.reshape(3, 4)

print("Reshaped Matrix:")
print(reshaped_arr)

Original Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshaped Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

C = np.matmul(A, B)

print(C)

[[19 22]
 [43 50]]


In [4]:
import numpy as np

A = np.array([
    [4, 2],
    [1, 3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [6]:
import numpy as np

data = np.random.rand(5, 3)

print("Random Dataset:")
print(data)

Random Dataset:
[[0.41263669 0.43194628 0.01026167]
 [0.82365907 0.68666283 0.45117383]
 [0.94573452 0.17381671 0.325683  ]
 [0.24106218 0.49960726 0.61356911]
 [0.20222923 0.49518193 0.47238028]]


In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

normalized_arr = (arr - np.min(arr)) / (
    np.max(arr) - np.min(arr)
)

print("Original Array:", arr)
print("Normalized Array:", normalized_arr)

Original Array: [10 20 30 40 50]
Normalized Array: [0.   0.25 0.5  0.75 1.  ]


In [10]:
import numpy as np

x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 55])

correlation_matrix = np.corrcoef(x, y)

correlation = correlation_matrix[0, 1]

print("Correlation:", correlation)

Correlation: 1.0


In [12]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['John', 'Alice', 'Bob'],
    'Age': [25, np.nan, 22]
})

df['Age'] = df['Age'].fillna(0)

print(df)

    Name   Age
0   John  25.0
1  Alice   0.0
2    Bob  22.0


In [13]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['John', 'Alice', 'Bob'],
    'Age': [25, np.nan, 22]
})

df = df.dropna()

print(df)

   Name   Age
0  John  25.0
2   Bob  22.0


In [14]:
import pandas as pd

data = {
    'Name': ['John', 'Alice', 'Bob'],
    'Age': [25, 18, 22]
}

df = pd.DataFrame(data)

result = df[df['Age'] > 20]

print(result)

   Name  Age
0  John   25
2   Bob   22


In [15]:
import pandas as pd

data = {
    'Name': ['John', 'Alice', 'John'],
    'Age': [25, 22, 25]
}

df = pd.DataFrame(data)

print("Duplicate Rows:")
print(df[df.duplicated()])

df = df.drop_duplicates()

print("After Removing Duplicates:")
print(df)

Duplicate Rows:
   Name  Age
2  John   25
After Removing Duplicates:
    Name  Age
0   John   25
1  Alice   22


In [16]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR'],
    'Salary': [50000, 60000, 45000, 55000]
}

df = pd.DataFrame(data)

result = df.groupby('Department')['Salary'].mean()

print(result)

Department
HR       50000.0
Sales    55000.0
Name: Salary, dtype: float64


In [17]:
import pandas as pd

data = {
    'Name': ['John', 'Alice', 'Bob'],
    'Department': ['IT', 'HR', 'IT'],
    'Age': [25, 22, 30]
}

df = pd.DataFrame(data)

result = df.sort_values(
    by=['Department', 'Age']
)

print(result)

    Name Department  Age
1  Alice         HR   22
0   John         IT   25
2    Bob         IT   30


In [18]:
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['John', 'Alice', 'Bob']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Marks': [85, 90, 78]
})

result = pd.merge(df1, df2, on='ID')

print(result)

   ID   Name  Marks
0   1   John     85
1   2  Alice     90
2   3    Bob     78


In [19]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [50000, 60000, 45000, 55000, 70000, 80000]
}

df = pd.DataFrame(data)

pivot = pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    aggfunc='mean'
)

print(pivot)

             Salary
Department         
HR          50000.0
IT          75000.0
Sales       55000.0


In [20]:
import pandas as pd

data = {
    'Age': [20, 25, 30, 35, 40],
    'Salary': [30000, 40000, 50000, 60000, 70000],
    'Experience': [1, 3, 5, 7, 9]
}

df = pd.DataFrame(data)

correlation_matrix = df.corr()

print(correlation_matrix)

            Age  Salary  Experience
Age         1.0     1.0         1.0
Salary      1.0     1.0         1.0
Experience  1.0     1.0         1.0


In [21]:
import pandas as pd

data = {
    'Age': [20, 25, 30, 35, 40],
    'Salary': [30000, 40000, 50000, 60000, 70000],
    'Experience': [1, 3, 5, 7, 9]
}

df = pd.DataFrame(data)

correlation_matrix = df.corr()

print(correlation_matrix)

            Age  Salary  Experience
Age         1.0     1.0         1.0
Salary      1.0     1.0         1.0
Experience  1.0     1.0         1.0
