<a href="https://colab.research.google.com/github/rachakondasaivarshini/DS-EXPS/blob/main/DS_exp8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create two vectors
A = np.array([2, 4, 6])
B = np.array([1, 3, 5])

# Vector Addition
addition = A + B

# Vector Subtraction
subtraction = A - B

# Scalar Multiplication
scalar = 3
scalar_multiplication = scalar * A

# Dot Product
dot_product = np.dot(A, B)

# Vector Magnitude
magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)

# Display results
print("Vector A:", A)
print("Vector B:", B)
print("Vector Addition:", addition)
print("Vector Subtraction:", subtraction)
print("Scalar Multiplication:", scalar_multiplication)
print("Dot Product:", dot_product)
print("Magnitude of A:", magnitude_A)
print("Magnitude of B:", magnitude_B)

Vector A: [2 4 6]
Vector B: [1 3 5]
Vector Addition: [ 3  7 11]
Vector Subtraction: [1 1 1]
Scalar Multiplication: [ 6 12 18]
Dot Product: 44
Magnitude of A: 7.483314773547883
Magnitude of B: 5.916079783099616


In [2]:
import numpy as np

# Create a matrix
A = np.array([[1, 2],
              [3, 4]])

# Calculate inverse
inverse_A = np.linalg.inv(A)

# Display results
print("Matrix A:")
print(A)

print("\nInverse of Matrix A:")
print(inverse_A)

# Verify A × A^-1 = Identity Matrix
print("\nA × A^-1:")
print(np.dot(A, inverse_A))

Matrix A:
[[1 2]
 [3 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

A × A^-1:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [3]:
import numpy as np

# Create a matrix
A = np.array([[1, 2],
              [3, 4]])

# Determinant
determinant = np.linalg.det(A)

# Rank
rank = np.linalg.matrix_rank(A)

# Trace
trace = np.trace(A)

# Display results
print("Matrix A:")
print(A)

print("\nDeterminant:", determinant)
print("Rank:", rank)
print("Trace:", trace)

Matrix A:
[[1 2]
 [3 4]]

Determinant: -2.0000000000000004
Rank: 2
Trace: 5


In [4]:
import numpy as np

# Create a square matrix
A = np.array([[2, 1],
              [1, 2]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display results
print("Matrix A:")
print(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrix A:
[[2 1]
 [1 2]]

Eigenvalues:
[3. 1.]

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
